### ISSUE TITLE
Crash when reading Ribbons

### ISSUE THREAD

**Issue by Koward** [Koward/jM2lib#1]
**Bless of Might spell** #by Uthil
```
java -jar jm2converter.jar -in SealOfMight_Impact_Base.m2 -out SealOfMight_Impact_Bases.m2 -cl
[[ Java M2 Converter by Koward v1.0.7-beta ]]
Exception in thread "main" java.io.EOFException
        at java.io.RandomAccessFile.readFully(Unknown Source)
        at com.mindprod.ledatastream.LERandomAccessFile.readChar(LERandomAccessFile.java:232)
        at jm2lib.io.UnmarshalingStream.readGeneric(UnmarshalingStream.java:75)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:134)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:128)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.wow.lichking.AnimationBlock.unmarshal(AnimationBlock.java:48)
        at jm2lib.blizzard.wow.lichking.Ribbon.unmarshal(Ribbon.java:64)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:132)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.wow.cataclysm.Model.unmarshal(Model.java:104)
        at jm2lib.blizzard.wow.M2.unmarshal(M2.java:63)
        at jm2lib.io.UnmarshalingStream.unmarshalObject(UnmarshalingStream.java:49)
        at jm2lib.blizzard.io.BlizzardInputStream.readObject(BlizzardInputStream.java:38)
        at koward.Main.main(Main.java:73)
```
**Chain of Ice spell** #by Uthil
```
-jar jm2converter.jar -in ChainsofIce_Low_Base.m2 -out ChainsofIce_Low_Bas.m2 -c
l
[[ Java M2 Converter by Koward v1.0.7-beta ]]
Exception in thread "main" java.io.EOFException
        at java.io.RandomAccessFile.readFully(Unknown Source)
        at com.mindprod.ledatastream.LERandomAccessFile.readChar(LERandomAccessFile.java:232)
        at jm2lib.io.UnmarshalingStream.readGeneric(UnmarshalingStream.java:75)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:134)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:128)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.wow.lichking.AnimationBlock.unmarshal(AnimationBlock.java:48)
        at jm2lib.blizzard.wow.lichking.Ribbon.unmarshal(Ribbon.java:64)
        at jm2lib.blizzard.common.types.ArrayRef.readContent(ArrayRef.java:132)
        at jm2lib.blizzard.common.types.ArrayRef.unmarshal(ArrayRef.java:93)
        at jm2lib.blizzard.wow.cataclysm.Model.unmarshal(Model.java:104)
        at jm2lib.blizzard.wow.M2.unmarshal(M2.java:63)
        at jm2lib.io.UnmarshalingStream.unmarshalObject(UnmarshalingStream.java:49)
        at jm2lib.blizzard.io.BlizzardInputStream.readObject(BlizzardInputStream.java:38)
        at koward.Main.main(Main.java:73)
```

**Comment by Koward** [comment]
Fixed it. The lib was not reading&writing the emission angle. Will be out for 1.0.8-b.
